### ISSUE TITLE
Demo Link?

### ISSUE THREAD

**Issue by axel-rank** [OleVik/grav-plugin-presentation#1]
Your Demo Link is broken:
Page not found.

![demo](https://user-images.githubusercontent.com/12480617/51308662-ec87d780-1a42-11e9-811b-c5574b691fa1.png)

**Comment by OleVik** [comment]
Yes, I haven't uploaded the skeleton yet. I'm compiling it today, so it will be there soon.

**Comment by OleVik** [comment]
The demo is now live at https://olevik.me/staging/grav-skeleton-presentation/.

**Comment by axza** [comment]
![image](https://user-images.githubusercontent.com/10170631/53942769-e796ea00-40bb-11e9-99bd-0bba066f4b4e.png)

**Comment by OleVik** [comment]
@axza Should be fixed now.
