### ISSUE TITLE
Export presentation

### ISSUE THREAD

**Issue by ghtmtt** [OleVik/grav-plugin-presentation#12]
Great plugin, thanks!

Is it possible to export the presentation for offline usage (e.g. to pdf)?

**Comment by OleVik** [comment]
Yes, by opening it in print-mode - just add `?print-pdf=true` to the URL of the presentation - and printing via the browser. The print-mode is Reveal.js' own, so it's made to look and feel like printing via PowerPoint. A demo: https://olevik.me/staging/grav-skeleton-presentation/?print-pdf=true.

Note that print-mode looks mostly horrible unless you're actually trying to print something - like to a PDF through Chrome. It also doesn't quite retain the look and feel of the presentation.
