### ISSUE TITLE
Background not changing

### ISSUE THREAD

**Issue by h4wkmoon** [OleVik/grav-plugin-presentation#18]
Hi, 

I've tried the files of your demo in my Grav (1.6) with your plugin.
The color of the background is forced to the reveal.js theme one.

The frontmatter has no effect.

What am I missing ? Can you help me plz ?

Regards, Fred.

**Comment by h4wkmoon** [comment]
Actually, none of the style options set in the frontmatter have an effect.

**Comment by h4wkmoon** [comment]
but shortcodes work

**Comment by OleVik** [comment]
This was a flaw in the Transport, it should be fixed in [v3.1.3](https://github.com/OleVik/grav-plugin-presentation/releases/tag/v3.1.3).
