### ISSUE TITLE
php7.0 support?

### ISSUE THREAD

**Issue by pcav** [OleVik/grav-plugin-presentation#2]
The plugin requires php7.1. Is this an hard requirement? Can it be overcome? The reason is that php7.0 is the newest version currently available for Debian stretch, now stable.
Thanks.

**Comment by OleVik** [comment]
This is a hard requirement, because Grav 1.6 [requires at least PHP v7.1.3](https://github.com/getgrav/grav/blob/1.6.0-beta.1/composer.json#L9).

[PHP v7.0.* reached End of Life](https://www.php.net/eol.php) two months ago, Debian really needs to catch up.

**Comment by pcav** [comment]
Thanks, and sorry for the noise.
