### ISSUE TITLE
Background Image not working (bad URL generated)

### ISSUE THREAD

**Issue by ulfben** [OleVik/grav-plugin-presentation#3]
I'm running Presentation v1.6.4 on Grav v1.6.3, and your Presentation Deckset v1.1.4. 

In the admin page editor there's a field under Design for "Background Image", however, it seems to generate bad URLs?

For example, I can upload "test.jpg" in my Page Media. If I add it to the page, like so: `![](test.jpg)` it renders a background image (courtesy of Deckset) with the path: 
`data-background-image="/basedir/user/pages/pagename/test.jpg"`

But if I try using the Background Image drop-down to select the image instead, the plugin now generate: 
`background-image: url("/pagename/test.jpg");`

Which of course is a 404. 

Is this a bug or am I missing some mod_rewrite magic or something else entirely?

**Comment by OleVik** [comment]
Probably a bug in accounting for system-setups. Could you describe how your Grav-installation is set up, ie. whether it runs from server root, a subfolder, or a subdomain? Is the first path, `/basedir/user/pages/pagename/test.jpg`, rendering the image correctly? The second one seems to have left out the base path, and I have an idea of where and why.

**Comment by ulfben** [comment]
The first path renders correctly, yes! 

I'm running apache2 on Ubuntu 18.04, with ssl (courtesy of letsencrypt)

- `DocumentRoot /var/www/`
- Grav is installed in `/var/www/basedir/ `
- `RewriteBase /basedir` is set in /var/www/basedir/.htaccess

(ergo. Grav is running a site in a humble sub-directory on the webserver)

**Comment by OleVik** [comment]
This should be fixed in the upcoming release.
