### ISSUE TITLE
Firefox / Chrome can't sync the presentation w/ speaker view

### ISSUE THREAD

**Issue by bonnebulle** [OleVik/grav-plugin-presentation#33]
Am following the Advanced instructions
https://github.com/OleVik/grav-plugin-presentation/blob/master/ADVANCED.md

`sync: 'poll'` or `sync: 'browser'`
Open my presentation :
`/presentation` ( _presentation view_ ) 
`/presentation?admin=true` ( _speaker view_ )

I try with Firefox and Chrome
opening _speaker view_ into an new window
...

But, when I change slides from _speaker view_, the slides into _presentation view_ dont changes...
I will retry later

Thanks for all
Reveal is very helpful

**Comment by OleVik** [comment]
Syncing with `sync: 'browser'` requires that you use the same browser for both presentation and speaker view, in separate windows. Which mode are you using? `sync: 'poll'` is especially server-dependent, where some setups will refuse polling altogether or time out of long-polling.

**Comment by bonnebulle** [comment]
Hum I try a few browsers (chromium + firefox) ... 
For exemple ... every time, like you say : 
- I open the speaker in Firefox (Window_0)
- I open the viewer in Firefox (Window_2)
but my interactions don't work, slides don't change.

**Comment by OleVik** [comment]
Do you get any errors in the browser's console, in either window? Despite it's apparent logic, it's a fairly [simple setup](https://github.com/OleVik/grav-plugin-presentation/blob/v4.0.3/js/broadcast.js) using a now [commonly available](https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API) browser API.

**Comment by bonnebulle** [comment]
Ok, thanks, I needed to set `sync: 'browser' ` like you said....
I had not read this information here (git Readme)
Sorry, I was the bug
Thanks again

**Comment by OleVik** [comment]
Glad it works!
