### ISSUE TITLE
Admin required?

### ISSUE THREAD

**Issue by rhukster** [OleVik/grav-plugin-presentation#8]
I was testing and don't have admin installed:

![Image 2019-05-08 at 11 48 49 AM](https://user-images.githubusercontent.com/1084697/57396274-4d205900-7187-11e9-9e37-479da4d1be01.png)

Admin is not in the dependencies so figured it would work fine without?

**Comment by OleVik** [comment]
Hmm, it shouldn't be handling the API without Admin even. I'll add the missing check for it.

**Comment by OleVik** [comment]
This should be fixed in v1.6.8, though I still suspect an upstream issue with `isAdmin()`.
